### ISSUE TITLE
Reduced Travis testing matrix.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/bioblend#121]
Test only 
 - dev with Python 2.6
 - dev with Python 2.7
 - release_15.03 with Python 2.7
 - release_15.01 with Python 2.7
 - release_14.10 with Python 2.7

See discussion here https://github.com/galaxyproject/bioblend/pull/120#issuecomment-77396084.

**Comment by erasche** [comment]
Probably something like:

```yaml
matrix:
  exclude:
    - python: 2.6
      env: release_15.03
    - python: 2.6
      env: release_15.01
    - python: 2.6
      env: release_14.10
```
